/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod/v4-mini'
import { safeParse } from '../lib/schemas.js'
import { Result as SafeParseResult } from '../types/fp.js'
import * as types from '../types/primitives.js'
import { SDKValidationError } from './errors/sdk-validation-error.js'

export type AIfetchChatResponseMessage = {}

export type AIfetchChatResponseData = {
  id?: string | undefined
  messages?: Array<AIfetchChatResponseMessage> | undefined
}

/**
 * Response returned when fetching a chat
 */
export type AIfetchChatResponse = {
  success: boolean
  data: AIfetchChatResponseData
}

/** @internal */
export const AIfetchChatResponseMessage$inboundSchema: z.ZodMiniType<
  AIfetchChatResponseMessage,
  unknown
> = z.object({})

export function aIfetchChatResponseMessageFromJSON(
  jsonString: string
): SafeParseResult<AIfetchChatResponseMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AIfetchChatResponseMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AIfetchChatResponseMessage' from JSON`
  )
}

/** @internal */
export const AIfetchChatResponseData$inboundSchema: z.ZodMiniType<
  AIfetchChatResponseData,
  unknown
> = z.object({
  id: types.optional(types.string()),
  messages: types.optional(z.array(z.lazy(() => AIfetchChatResponseMessage$inboundSchema))),
})

export function aIfetchChatResponseDataFromJSON(
  jsonString: string
): SafeParseResult<AIfetchChatResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AIfetchChatResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AIfetchChatResponseData' from JSON`
  )
}

/** @internal */
export const AIfetchChatResponse$inboundSchema: z.ZodMiniType<AIfetchChatResponse, unknown> =
  z.object({
    success: types.boolean(),
    data: z.lazy(() => AIfetchChatResponseData$inboundSchema),
  })

export function aIfetchChatResponseFromJSON(
  jsonString: string
): SafeParseResult<AIfetchChatResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AIfetchChatResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AIfetchChatResponse' from JSON`
  )
}
