/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod/v4-mini'
import { safeParse } from '../lib/schemas.js'
import { Result as SafeParseResult } from '../types/fp.js'
import * as types from '../types/primitives.js'
import { SDKValidationError } from './errors/sdk-validation-error.js'

export type AIChatOptionResponseData = {
  /**
   * Unique identifier for the AI options record
   */
  id: string
  /**
   * Foreign key reference to chat_types table
   */
  chatTypeId: string
  /**
   * The prompt template for the AI model
   */
  prompt: string
  /**
   * Maximum number of tokens to generate
   */
  maxTokens?: number | null | undefined
  /**
   * Sampling temperature for randomness (0 = deterministic, 2 = very random)
   */
  temperature?: number | null | undefined
  /**
   * Nucleus sampling threshold (0-1)
   */
  topP?: number | null | undefined
  /**
   * Penalty for repeating words/phrases (-2 to 2)
   */
  frequencyPenalty?: number | null | undefined
  /**
   * Penalty for repeating information from prompt (-2 to 2)
   */
  presencePenalty?: number | null | undefined
  /**
   * Top-K sampling parameter
   */
  topK?: number | null | undefined
  /**
   * Array of sequences that stop text generation
   */
  stopSequences?: Array<string> | null | undefined
  /**
   * Random seed for deterministic results
   */
  seed?: number | null | undefined
  /**
   * Maximum number of retries for transient errors
   */
  maxRetries?: number | null | undefined
  /**
   * Timestamp when the record was created
   */
  createdAt: Date
  /**
   * Timestamp when the record was last updated
   */
  updatedAt: Date
}

/**
 * Response returned when fetching a specific chat AI option configuration
 */
export type AIChatOptionResponse = {
  success: boolean
  data: AIChatOptionResponseData
}

/** @internal */
export const AIChatOptionResponseData$inboundSchema: z.ZodMiniType<
  AIChatOptionResponseData,
  unknown
> = z.object({
  id: types.string(),
  chatTypeId: types.string(),
  prompt: types.string(),
  maxTokens: z.optional(z.nullable(types.number())),
  temperature: z.optional(z.nullable(types.number())),
  topP: z.optional(z.nullable(types.number())),
  frequencyPenalty: z.optional(z.nullable(types.number())),
  presencePenalty: z.optional(z.nullable(types.number())),
  topK: z.optional(z.nullable(types.number())),
  stopSequences: z.optional(z.nullable(z.array(types.string()))),
  seed: z.optional(z.nullable(types.number())),
  maxRetries: z.optional(z.nullable(types.number())),
  createdAt: types.date(),
  updatedAt: types.date(),
})

export function aiChatOptionResponseDataFromJSON(
  jsonString: string
): SafeParseResult<AIChatOptionResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AIChatOptionResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AIChatOptionResponseData' from JSON`
  )
}

/** @internal */
export const AIChatOptionResponse$inboundSchema: z.ZodMiniType<AIChatOptionResponse, unknown> =
  z.object({
    success: types.boolean(),
    data: z.lazy(() => AIChatOptionResponseData$inboundSchema),
  })

export function aiChatOptionResponseFromJSON(
  jsonString: string
): SafeParseResult<AIChatOptionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AIChatOptionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AIChatOptionResponse' from JSON`
  )
}
