/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type AIChatOptionsResponseData = {
  id: string;
  /**
   * Name of the chat type
   */
  name: string;
  /**
   * Description of the chat type purpose
   */
  description: string;
  createdAt: Date;
  updatedAt: Date;
  /**
   * SEO friendly slug for the chat type
   */
  seoFriendlyId: string;
  /**
   * Base64url encoded UUID for the chat type (22 characters)
   */
  seoFriendlyBase64Id: string;
};

/**
 * Response returned when fetching AI chat options
 */
export type AIChatOptionsResponse = {
  success: boolean;
  data: Array<AIChatOptionsResponseData>;
};

/** @internal */
export const AIChatOptionsResponseData$inboundSchema: z.ZodMiniType<
  AIChatOptionsResponseData,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
  description: types.string(),
  createdAt: types.date(),
  updatedAt: types.date(),
  seoFriendlyId: types.string(),
  seoFriendlyBase64Id: types.string(),
});

export function aiChatOptionsResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<AIChatOptionsResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AIChatOptionsResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AIChatOptionsResponseData' from JSON`,
  );
}

/** @internal */
export const AIChatOptionsResponse$inboundSchema: z.ZodMiniType<
  AIChatOptionsResponse,
  unknown
> = z.object({
  success: types.boolean(),
  data: z.array(z.lazy(() => AIChatOptionsResponseData$inboundSchema)),
});

export function aiChatOptionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<AIChatOptionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AIChatOptionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AIChatOptionsResponse' from JSON`,
  );
}
