/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod/v4-mini'
import { ClosedEnum } from '../types/enums.js'

export const AIRequestRole = {
  User: 'user',
  Assistant: 'assistant',
} as const
export type AIRequestRole = ClosedEnum<typeof AIRequestRole>

export const Type = {
  Text: 'text',
  StepStart: 'step-start',
} as const
export type Type = ClosedEnum<typeof Type>

export const State = {
  Done: 'done',
} as const
export type State = ClosedEnum<typeof State>

export type Part = {
  type: Type
  text?: string | undefined
  state?: State | undefined
}

export type AIRequestMessage = {
  id: string
  role: AIRequestRole
  parts: Array<Part>
}

/**
 * AI-generated response object
 */
export type AIRequest = {
  id: string
  messages: Array<AIRequestMessage>
  /**
   * Indicates which user or system action caused this AI response to be generated. Implementations should use consistent, machine-readable identifiers (e.g. "submit-message").
   */
  trigger: string
}

/** @internal */
export const AIRequestRole$outboundSchema: z.ZodMiniEnum<typeof AIRequestRole> =
  z.enum(AIRequestRole)

/** @internal */
export const Type$outboundSchema: z.ZodMiniEnum<typeof Type> = z.enum(Type)

/** @internal */
export const State$outboundSchema: z.ZodMiniEnum<typeof State> = z.enum(State)

/** @internal */
export type Part$Outbound = {
  type: string
  text?: string | undefined
  state?: string | undefined
}

/** @internal */
export const Part$outboundSchema: z.ZodMiniType<Part$Outbound, Part> = z.object({
  type: Type$outboundSchema,
  text: z.optional(z.string()),
  state: z.optional(State$outboundSchema),
})

export function partToJSON(part: Part): string {
  return JSON.stringify(Part$outboundSchema.parse(part))
}

/** @internal */
export type AIRequestMessage$Outbound = {
  id: string
  role: string
  parts: Array<Part$Outbound>
}

/** @internal */
export const AIRequestMessage$outboundSchema: z.ZodMiniType<
  AIRequestMessage$Outbound,
  AIRequestMessage
> = z.object({
  id: z.string(),
  role: AIRequestRole$outboundSchema,
  parts: z.array(z.lazy(() => Part$outboundSchema)),
})

export function aiRequestMessageToJSON(aiRequestMessage: AIRequestMessage): string {
  return JSON.stringify(AIRequestMessage$outboundSchema.parse(aiRequestMessage))
}

/** @internal */
export type AIRequest$Outbound = {
  id: string
  messages: Array<AIRequestMessage$Outbound>
  trigger: string
}

/** @internal */
export const AIRequest$outboundSchema: z.ZodMiniType<AIRequest$Outbound, AIRequest> = z.object({
  id: z.string(),
  messages: z.array(z.lazy(() => AIRequestMessage$outboundSchema)),
  trigger: z.string(),
})

export function aiRequestToJSON(aiRequest: AIRequest): string {
  return JSON.stringify(AIRequest$outboundSchema.parse(aiRequest))
}
