/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Structured response containing array of chat IDs for a user
 */
export type AIUserIdResponse = {
  /**
   * Indicates if the request was successful
   */
  success: boolean;
  /**
   * Array of UUID strings for previous AI chats
   */
  data: Array<string>;
};

/** @internal */
export const AIUserIdResponse$inboundSchema: z.ZodMiniType<
  AIUserIdResponse,
  unknown
> = z.object({
  success: types.boolean(),
  data: z.array(types.string()),
});

export function aiUserIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<AIUserIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AIUserIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AIUserIdResponse' from JSON`,
  );
}
