/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ChatTypesResponseData = {
  /**
   * Unique identifier for the chat type
   */
  id: string;
  /**
   * Display name of the chat type
   */
  name: string;
  /**
   * SEO-friendly URL slug (lowercase alphanumeric with hyphens)
   */
  seoFriendlyId: string;
  /**
   * Base64-encoded URL-safe identifier (22 characters)
   */
  seoFriendlyBase64Id: string;
  /**
   * Detailed description of the chat type
   */
  description: string;
  /**
   * Timestamp when the chat type was created
   */
  createdAt: Date;
  /**
   * Timestamp when the chat type was last updated
   */
  updatedAt: Date;
};

/**
 * Structured response containing array of chat types
 */
export type ChatTypesResponse = {
  /**
   * Indicates if the request was successful
   */
  success: boolean;
  /**
   * Array of chat type objects
   */
  data: Array<ChatTypesResponseData>;
};

/** @internal */
export const ChatTypesResponseData$inboundSchema: z.ZodMiniType<
  ChatTypesResponseData,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
  seoFriendlyId: types.string(),
  seoFriendlyBase64Id: types.string(),
  description: types.string(),
  createdAt: types.date(),
  updatedAt: types.date(),
});

export function chatTypesResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<ChatTypesResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatTypesResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatTypesResponseData' from JSON`,
  );
}

/** @internal */
export const ChatTypesResponse$inboundSchema: z.ZodMiniType<
  ChatTypesResponse,
  unknown
> = z.object({
  success: types.boolean(),
  data: z.array(z.lazy(() => ChatTypesResponseData$inboundSchema)),
});

export function chatTypesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ChatTypesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatTypesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatTypesResponse' from JSON`,
  );
}
