/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod/v4-mini'
import { safeParse } from '../lib/schemas.js'
import * as openEnums from '../types/enums.js'
import { OpenEnum } from '../types/enums.js'
import { Result as SafeParseResult } from '../types/fp.js'
import * as types from '../types/primitives.js'
import { SDKValidationError } from './errors/sdk-validation-error.js'

/**
 * Current status of the company
 */
export const CompanyDetailsResponseStatus = {
  Prospect: 'prospect',
  Active: 'active',
  Paused: 'paused',
  Churned: 'churned',
} as const
/**
 * Current status of the company
 */
export type CompanyDetailsResponseStatus = OpenEnum<typeof CompanyDetailsResponseStatus>

/**
 * Company details
 */
export type CompanyDetailsResponseCompany = {
  /**
   * Unique identifier for the company
   */
  companyId: string
  /**
   * Legal name of the company
   */
  legalName: string
  /**
   * Display name of the company
   */
  displayName: string
  /**
   * Current status of the company
   */
  status: CompanyDetailsResponseStatus
  /**
   * Industry sector
   */
  industry?: string | null | undefined
  /**
   * Number of employees
   */
  companySize?: number | null | undefined
  /**
   * Company website URL
   */
  websiteUrl?: string | null | undefined
  /**
   * ISO 3166-1 alpha-2 country code
   */
  billingCountry?: string | null | undefined
  /**
   * Company timezone
   */
  timezone: string
  /**
   * Timestamp when the company record was created
   */
  createdAt: Date
  /**
   * Timestamp when the company record was last updated
   */
  updatedAt: Date
}

/**
 * Key person contact details
 */
export type CompanyDetailsResponseKeyPerson = {
  /**
   * Unique identifier for the key person
   */
  keyPersonId: string
  /**
   * First name of the key person
   */
  firstName: string
  /**
   * Last name of the key person
   */
  lastName: string
  /**
   * Email address (case-insensitive)
   */
  email?: string | null | undefined
  /**
   * Phone number
   */
  phone?: string | null | undefined
  /**
   * Job title
   */
  jobTitle?: string | null | undefined
  /**
   * Whether the key person is currently active. This field has a database default of true and will always be present in responses unless explicitly set to false.
   */
  isActive: boolean
  /**
   * Timestamp when the key person record was created
   */
  createdAt: Date
  /**
   * Timestamp when the key person record was last updated
   */
  updatedAt: Date
}

/**
 * Company and key person information
 */
export type CompanyDetailsResponseData = {
  /**
   * Company details
   */
  company: CompanyDetailsResponseCompany
  /**
   * Key person contact details
   */
  keyPerson: CompanyDetailsResponseKeyPerson
}

/**
 * Structured response containing company and key person details
 */
export type CompanyDetailsResponse = {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Company and key person information
   */
  data: CompanyDetailsResponseData
}

/** @internal */
export const CompanyDetailsResponseStatus$inboundSchema: z.ZodMiniType<
  CompanyDetailsResponseStatus,
  unknown
> = openEnums.inboundSchema(CompanyDetailsResponseStatus)

/** @internal */
export const CompanyDetailsResponseCompany$inboundSchema: z.ZodMiniType<
  CompanyDetailsResponseCompany,
  unknown
> = z.object({
  companyId: types.string(),
  legalName: types.string(),
  displayName: types.string(),
  status: CompanyDetailsResponseStatus$inboundSchema,
  industry: z.optional(z.nullable(types.string())),
  companySize: z.optional(z.nullable(types.number())),
  websiteUrl: z.optional(z.nullable(types.string())),
  billingCountry: z.optional(z.nullable(types.string())),
  timezone: types.string(),
  createdAt: types.date(),
  updatedAt: types.date(),
})

export function companyDetailsResponseCompanyFromJSON(
  jsonString: string
): SafeParseResult<CompanyDetailsResponseCompany, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompanyDetailsResponseCompany$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompanyDetailsResponseCompany' from JSON`
  )
}

/** @internal */
export const CompanyDetailsResponseKeyPerson$inboundSchema: z.ZodMiniType<
  CompanyDetailsResponseKeyPerson,
  unknown
> = z.object({
  keyPersonId: types.string(),
  firstName: types.string(),
  lastName: types.string(),
  email: z.optional(z.nullable(types.string())),
  phone: z.optional(z.nullable(types.string())),
  jobTitle: z.optional(z.nullable(types.string())),
  isActive: types.boolean(),
  createdAt: types.date(),
  updatedAt: types.date(),
})

export function companyDetailsResponseKeyPersonFromJSON(
  jsonString: string
): SafeParseResult<CompanyDetailsResponseKeyPerson, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompanyDetailsResponseKeyPerson$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompanyDetailsResponseKeyPerson' from JSON`
  )
}

/** @internal */
export const CompanyDetailsResponseData$inboundSchema: z.ZodMiniType<
  CompanyDetailsResponseData,
  unknown
> = z.object({
  company: z.lazy(() => CompanyDetailsResponseCompany$inboundSchema),
  keyPerson: z.lazy(() => CompanyDetailsResponseKeyPerson$inboundSchema),
})

export function companyDetailsResponseDataFromJSON(
  jsonString: string
): SafeParseResult<CompanyDetailsResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompanyDetailsResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompanyDetailsResponseData' from JSON`
  )
}

/** @internal */
export const CompanyDetailsResponse$inboundSchema: z.ZodMiniType<CompanyDetailsResponse, unknown> =
  z.object({
    success: types.boolean(),
    data: z.lazy(() => CompanyDetailsResponseData$inboundSchema),
  })

export function companyDetailsResponseFromJSON(
  jsonString: string
): SafeParseResult<CompanyDetailsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompanyDetailsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompanyDetailsResponse' from JSON`
  )
}
