/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod/v4-mini'
import { ClosedEnum } from '../types/enums.js'

/**
 * Current status of the company
 */
export const CompanyDetailsRequestStatus = {
  Prospect: 'prospect',
  Active: 'active',
  Paused: 'paused',
  Churned: 'churned',
} as const
/**
 * Current status of the company
 */
export type CompanyDetailsRequestStatus = ClosedEnum<typeof CompanyDetailsRequestStatus>

/**
 * Company details
 */
export type CompanyDetailsRequestCompany = {
  /**
   * Unique identifier for the company
   */
  companyId: string
  /**
   * Legal name of the company
   */
  legalName?: string | undefined
  /**
   * Display name of the company
   */
  displayName?: string | undefined
  /**
   * Current status of the company
   */
  status?: CompanyDetailsRequestStatus | undefined
  /**
   * Industry sector
   */
  industry?: string | null | undefined
  /**
   * Number of employees
   */
  companySize?: number | null | undefined
  /**
   * Company website URL
   */
  websiteUrl?: string | null | undefined
  /**
   * ISO 3166-1 alpha-2 country code
   */
  billingCountry?: string | null | undefined
  /**
   * Company timezone
   */
  timezone?: string | undefined
}

/**
 * Key person contact details
 */
export type CompanyDetailsRequestKeyPerson = {
  /**
   * Unique identifier for the key person
   */
  keyPersonId: string
  /**
   * First name of the key person
   */
  firstName?: string | undefined
  /**
   * Last name of the key person
   */
  lastName?: string | undefined
  /**
   * Email address (case-insensitive)
   */
  email?: string | null | undefined
  /**
   * Phone number
   */
  phone?: string | null | undefined
  /**
   * Job title
   */
  jobTitle?: string | null | undefined
  /**
   * Whether the key person is currently active. This field has a database default of true and will always be present in responses unless explicitly set to false.
   */
  isActive?: boolean | undefined
}

/**
 * Structured request containing company and key person details
 */
export type CompanyDetailsRequest = {
  /**
   * Company details
   */
  company?: CompanyDetailsRequestCompany | undefined
  /**
   * Key person contact details
   */
  keyPerson?: CompanyDetailsRequestKeyPerson | undefined
}

/** @internal */
export const CompanyDetailsRequestStatus$outboundSchema: z.ZodMiniEnum<
  typeof CompanyDetailsRequestStatus
> = z.enum(CompanyDetailsRequestStatus)

/** @internal */
export type CompanyDetailsRequestCompany$Outbound = {
  companyId: string
  legalName?: string | undefined
  displayName?: string | undefined
  status?: string | undefined
  industry?: string | null | undefined
  companySize?: number | null | undefined
  websiteUrl?: string | null | undefined
  billingCountry?: string | null | undefined
  timezone?: string | undefined
}

/** @internal */
export const CompanyDetailsRequestCompany$outboundSchema: z.ZodMiniType<
  CompanyDetailsRequestCompany$Outbound,
  CompanyDetailsRequestCompany
> = z.object({
  companyId: z.string(),
  legalName: z.optional(z.string()),
  displayName: z.optional(z.string()),
  status: z.optional(CompanyDetailsRequestStatus$outboundSchema),
  industry: z.optional(z.nullable(z.string())),
  companySize: z.optional(z.nullable(z.int())),
  websiteUrl: z.optional(z.nullable(z.string())),
  billingCountry: z.optional(z.nullable(z.string())),
  timezone: z.optional(z.string()),
})

export function companyDetailsRequestCompanyToJSON(
  companyDetailsRequestCompany: CompanyDetailsRequestCompany
): string {
  return JSON.stringify(
    CompanyDetailsRequestCompany$outboundSchema.parse(companyDetailsRequestCompany)
  )
}

/** @internal */
export type CompanyDetailsRequestKeyPerson$Outbound = {
  keyPersonId: string
  firstName?: string | undefined
  lastName?: string | undefined
  email?: string | null | undefined
  phone?: string | null | undefined
  jobTitle?: string | null | undefined
  isActive?: boolean | undefined
}

/** @internal */
export const CompanyDetailsRequestKeyPerson$outboundSchema: z.ZodMiniType<
  CompanyDetailsRequestKeyPerson$Outbound,
  CompanyDetailsRequestKeyPerson
> = z.object({
  keyPersonId: z.string(),
  firstName: z.optional(z.string()),
  lastName: z.optional(z.string()),
  email: z.optional(z.nullable(z.string())),
  phone: z.optional(z.nullable(z.string())),
  jobTitle: z.optional(z.nullable(z.string())),
  isActive: z.optional(z.boolean()),
})

export function companyDetailsRequestKeyPersonToJSON(
  companyDetailsRequestKeyPerson: CompanyDetailsRequestKeyPerson
): string {
  return JSON.stringify(
    CompanyDetailsRequestKeyPerson$outboundSchema.parse(companyDetailsRequestKeyPerson)
  )
}

/** @internal */
export type CompanyDetailsRequest$Outbound = {
  company?: CompanyDetailsRequestCompany$Outbound | undefined
  keyPerson?: CompanyDetailsRequestKeyPerson$Outbound | undefined
}

/** @internal */
export const CompanyDetailsRequest$outboundSchema: z.ZodMiniType<
  CompanyDetailsRequest$Outbound,
  CompanyDetailsRequest
> = z.object({
  company: z.optional(z.lazy(() => CompanyDetailsRequestCompany$outboundSchema)),
  keyPerson: z.optional(z.lazy(() => CompanyDetailsRequestKeyPerson$outboundSchema)),
})

export function companyDetailsRequestToJSON(companyDetailsRequest: CompanyDetailsRequest): string {
  return JSON.stringify(CompanyDetailsRequest$outboundSchema.parse(companyDetailsRequest))
}
