/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod/v4-mini'
import { safeParse } from '../lib/schemas.js'
import { Result as SafeParseResult } from '../types/fp.js'
import * as types from '../types/primitives.js'
import { SDKValidationError } from './errors/sdk-validation-error.js'

/**
 * Response returned after successful OAuth user synchronization
 */
export type OAuthSyncResponse = {
  success: boolean
  /**
   * Success message confirming the sync operation
   */
  message: string
}

/** @internal */
export const OAuthSyncResponse$inboundSchema: z.ZodMiniType<OAuthSyncResponse, unknown> = z.object({
  success: types.boolean(),
  message: types.string(),
})

export function oAuthSyncResponseFromJSON(
  jsonString: string
): SafeParseResult<OAuthSyncResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OAuthSyncResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OAuthSyncResponse' from JSON`
  )
}
