/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Request payload for OAuth user synchronization
 */
export type OAuthSyncRequest = {
  /**
   * OAuth provider name (e.g., 'google', 'github')
   */
  provider: string;
  /**
   * User ID from OAuth provider
   */
  providerId: string;
  /**
   * User's email address from OAuth provider
   */
  email: string;
  /**
   * User's display name from OAuth provider (optional)
   */
  name?: string | undefined;
};

/** @internal */
export type OAuthSyncRequest$Outbound = {
  provider: string;
  providerId: string;
  email: string;
  name?: string | undefined;
};

/** @internal */
export const OAuthSyncRequest$outboundSchema: z.ZodMiniType<
  OAuthSyncRequest$Outbound,
  OAuthSyncRequest
> = z.object({
  provider: z.string(),
  providerId: z.string(),
  email: z.string(),
  name: z.optional(z.string()),
});

export function oAuthSyncRequestToJSON(
  oAuthSyncRequest: OAuthSyncRequest,
): string {
  return JSON.stringify(
    OAuthSyncRequest$outboundSchema.parse(oAuthSyncRequest),
  );
}
