/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { User, User$inboundSchema } from "./user.js";

export type Pagination = {
  /**
   * Number of items to skip
   */
  offset: number;
  /**
   * Number of items per page
   */
  limit: number;
  /**
   * Total number of users
   */
  total: number;
};

/**
 * Paginated response for users list
 */
export type PaginatedUsersResponse = {
  success: boolean;
  data: Array<User>;
  pagination: Pagination;
};

/** @internal */
export const Pagination$inboundSchema: z.ZodMiniType<Pagination, unknown> = z
  .object({
    offset: types.number(),
    limit: types.number(),
    total: types.number(),
  });

export function paginationFromJSON(
  jsonString: string,
): SafeParseResult<Pagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Pagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Pagination' from JSON`,
  );
}

/** @internal */
export const PaginatedUsersResponse$inboundSchema: z.ZodMiniType<
  PaginatedUsersResponse,
  unknown
> = z.object({
  success: types.boolean(),
  data: z.array(User$inboundSchema),
  pagination: z.lazy(() => Pagination$inboundSchema),
});

export function paginatedUsersResponseFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedUsersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaginatedUsersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedUsersResponse' from JSON`,
  );
}
