/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Settings for AI chat requests
 */
export type PutRequestAIChatSettings = {
  /**
   * The prompt template for the AI model
   */
  prompt: string;
  /**
   * Maximum number of tokens to generate
   */
  maxTokens?: number | null | undefined;
  /**
   * Sampling temperature for randomness (0 = deterministic, 2 = very random)
   */
  temperature?: number | null | undefined;
  /**
   * Nucleus sampling threshold (0-1)
   */
  topP?: number | null | undefined;
  /**
   * Penalty for repeating words/phrases (-2 to 2)
   */
  frequencyPenalty?: number | null | undefined;
  /**
   * Penalty for repeating information from prompt (-2 to 2)
   */
  presencePenalty?: number | null | undefined;
  /**
   * Top-K sampling parameter
   */
  topK?: number | null | undefined;
  /**
   * Array of sequences that stop text generation
   */
  stopSequences?: Array<string> | null | undefined;
  /**
   * Random seed for deterministic results
   */
  seed?: number | null | undefined;
  /**
   * Maximum number of retries for transient errors
   */
  maxRetries?: number | null | undefined;
};

/** @internal */
export type PutRequestAIChatSettings$Outbound = {
  prompt: string;
  maxTokens?: number | null | undefined;
  temperature?: number | null | undefined;
  topP?: number | null | undefined;
  frequencyPenalty?: number | null | undefined;
  presencePenalty?: number | null | undefined;
  topK?: number | null | undefined;
  stopSequences?: Array<string> | null | undefined;
  seed?: number | null | undefined;
  maxRetries?: number | null | undefined;
};

/** @internal */
export const PutRequestAIChatSettings$outboundSchema: z.ZodMiniType<
  PutRequestAIChatSettings$Outbound,
  PutRequestAIChatSettings
> = z.object({
  prompt: z.string(),
  maxTokens: z.optional(z.nullable(z.int())),
  temperature: z.optional(z.nullable(z.number())),
  topP: z.optional(z.nullable(z.number())),
  frequencyPenalty: z.optional(z.nullable(z.number())),
  presencePenalty: z.optional(z.nullable(z.number())),
  topK: z.optional(z.nullable(z.int())),
  stopSequences: z.optional(z.nullable(z.array(z.string()))),
  seed: z.optional(z.nullable(z.int())),
  maxRetries: z.optional(z.nullable(z.int())),
});

export function putRequestAIChatSettingsToJSON(
  putRequestAIChatSettings: PutRequestAIChatSettings,
): string {
  return JSON.stringify(
    PutRequestAIChatSettings$outboundSchema.parse(putRequestAIChatSettings),
  );
}
