/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Registration result data
 */
export type RegisterUserResponseData = {
  userId: string;
  /**
   * JWT access token
   */
  accessToken: string;
  /**
   * Type of the token
   */
  tokenType?: string | undefined;
  /**
   * How long the user token lasts for
   */
  expiresIn?: number | undefined;
};

/**
 * Response returned after successful user registration
 */
export type RegisterUserResponse = {
  success: boolean;
  /**
   * Registration result data
   */
  data: RegisterUserResponseData;
};

/** @internal */
export const RegisterUserResponseData$inboundSchema: z.ZodMiniType<
  RegisterUserResponseData,
  unknown
> = z.pipe(
  z.object({
    userId: types.string(),
    access_token: types.string(),
    token_type: types.optional(types.string()),
    expires_in: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "access_token": "accessToken",
      "token_type": "tokenType",
      "expires_in": "expiresIn",
    });
  }),
);

export function registerUserResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<RegisterUserResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RegisterUserResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RegisterUserResponseData' from JSON`,
  );
}

/** @internal */
export const RegisterUserResponse$inboundSchema: z.ZodMiniType<
  RegisterUserResponse,
  unknown
> = z.object({
  success: types.boolean(),
  data: z.lazy(() => RegisterUserResponseData$inboundSchema),
});

export function registerUserResponseFromJSON(
  jsonString: string,
): SafeParseResult<RegisterUserResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RegisterUserResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RegisterUserResponse' from JSON`,
  );
}
