/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Request payload for registering a new user
 */
export type RegisterUserRequest = {
  /**
   * User's email address
   */
  email: string;
  /**
   * User's password (minimum 12 characters)
   */
  password: string;
  /**
   * User's full name
   */
  name: string;
};

/** @internal */
export type RegisterUserRequest$Outbound = {
  email: string;
  password: string;
  name: string;
};

/** @internal */
export const RegisterUserRequest$outboundSchema: z.ZodMiniType<
  RegisterUserRequest$Outbound,
  RegisterUserRequest
> = z.object({
  email: z.string(),
  password: z.string(),
  name: z.string(),
});

export function registerUserRequestToJSON(
  registerUserRequest: RegisterUserRequest,
): string {
  return JSON.stringify(
    RegisterUserRequest$outboundSchema.parse(registerUserRequest),
  );
}
