/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod/v4-mini'

/**
 * Request payload for user authentication
 */
export type UserLoginRequest = {
  /**
   * User's email address
   */
  email: string
  /**
   * User's password
   */
  password: string
}

/** @internal */
export type UserLoginRequest$Outbound = {
  email: string
  password: string
}

/** @internal */
export const UserLoginRequest$outboundSchema: z.ZodMiniType<
  UserLoginRequest$Outbound,
  UserLoginRequest
> = z.object({
  email: z.string(),
  password: z.string(),
})

export function userLoginRequestToJSON(userLoginRequest: UserLoginRequest): string {
  return JSON.stringify(UserLoginRequest$outboundSchema.parse(userLoginRequest))
}
