/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod/v4-mini'
import { remap as remap$ } from '../lib/primitives.js'
import { safeParse } from '../lib/schemas.js'
import * as openEnums from '../types/enums.js'
import { OpenEnum } from '../types/enums.js'
import { Result as SafeParseResult } from '../types/fp.js'
import * as types from '../types/primitives.js'
import { SDKValidationError } from './errors/sdk-validation-error.js'

export const UserLoginResponseRole = {
  User: 'user',
  Admin: 'admin',
  Moderator: 'moderator',
} as const
export type UserLoginResponseRole = OpenEnum<typeof UserLoginResponseRole>

/**
 * Authentication result data
 */
export type UserLoginResponseData = {
  /**
   * The authenticated user's unique identifier
   */
  userId: string
  /**
   * The authenticated user's email address
   */
  email: string
  /**
   * JWT access token for authenticated requests
   */
  accessToken: string
  /**
   * User's assigned roles
   */
  roles: Array<UserLoginResponseRole>
}

/**
 * Response returned after successful user authentication
 */
export type UserLoginResponse = {
  success: boolean
  /**
   * Authentication result data
   */
  data: UserLoginResponseData
}

/** @internal */
export const UserLoginResponseRole$inboundSchema: z.ZodMiniType<UserLoginResponseRole, unknown> =
  openEnums.inboundSchema(UserLoginResponseRole)

/** @internal */
export const UserLoginResponseData$inboundSchema: z.ZodMiniType<UserLoginResponseData, unknown> =
  z.pipe(
    z.object({
      userId: types.string(),
      email: types.string(),
      access_token: types.string(),
      roles: z.array(UserLoginResponseRole$inboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        access_token: 'accessToken',
      })
    })
  )

export function userLoginResponseDataFromJSON(
  jsonString: string
): SafeParseResult<UserLoginResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserLoginResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserLoginResponseData' from JSON`
  )
}

/** @internal */
export const UserLoginResponse$inboundSchema: z.ZodMiniType<UserLoginResponse, unknown> = z.object({
  success: types.boolean(),
  data: z.lazy(() => UserLoginResponseData$inboundSchema),
})

export function userLoginResponseFromJSON(
  jsonString: string
): SafeParseResult<UserLoginResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserLoginResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserLoginResponse' from JSON`
  )
}
