/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod/v4-mini'
import { safeParse } from '../lib/schemas.js'
import * as openEnums from '../types/enums.js'
import { OpenEnum } from '../types/enums.js'
import { Result as SafeParseResult } from '../types/fp.js'
import * as types from '../types/primitives.js'
import { SDKValidationError } from './errors/sdk-validation-error.js'

/**
 * User's role in the system
 */
export const UserRole = {
  User: 'user',
  Admin: 'admin',
  Moderator: 'moderator',
} as const
/**
 * User's role in the system
 */
export type UserRole = OpenEnum<typeof UserRole>

/**
 * User profile information
 */
export type User = {
  id: string
  email: string
  name: string
  /**
   * User's role in the system
   */
  role: UserRole
  createdAt: Date
}

/** @internal */
export const UserRole$inboundSchema: z.ZodMiniType<UserRole, unknown> =
  openEnums.inboundSchema(UserRole)

/** @internal */
export const User$inboundSchema: z.ZodMiniType<User, unknown> = z.object({
  id: types.string(),
  email: types.string(),
  name: types.string(),
  role: UserRole$inboundSchema,
  createdAt: types.date(),
})

export function userFromJSON(jsonString: string): SafeParseResult<User, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => User$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'User' from JSON`
  )
}
