/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from 'dotenv'
dotenv.config()
/**
 * Example usage of the norberts-spark-sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx healthGetHealth.example.ts
 */

import { NorbertsSparkSDK } from 'norberts-spark-sdk'

const norbertsSparkSDK = new NorbertsSparkSDK({
  bearerAuth: process.env['NORBERTSSPARKSDK_BEARER_AUTH'] ?? '',
})

async function main() {
  const result = await norbertsSparkSDK.health.getHealth()

  console.log(result)
}

main().catch(console.error)
