/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod/v4-mini'
import * as types from '../../types/primitives.js'
import { NorbertsSparkSDKError } from './norberts-spark-sdk-error.js'

/**
 * Standard error response object
 */
export type ErrorTData = {
  success: boolean
  error: string
}

/**
 * Standard error response object
 */
export class ErrorT extends NorbertsSparkSDKError {
  success: boolean
  error: string

  /** The original data that was passed to this error instance. */
  data$: ErrorTData

  constructor(err: ErrorTData, httpMeta: { response: Response; request: Request; body: string }) {
    const message =
      'message' in err && typeof err.message === 'string'
        ? err.message
        : `API error occurred: ${JSON.stringify(err)}`
    super(message, httpMeta)
    this.data$ = err
    this.success = err.success
    this.error = err.error

    this.name = 'ErrorT'
  }
}

/** @internal */
export const ErrorT$inboundSchema: z.ZodMiniType<ErrorT, unknown> = z.pipe(
  z.object({
    success: types.boolean(),
    error: types.string(),
    request$: z.custom<Request>((x) => x instanceof Request),
    response$: z.custom<Response>((x) => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ErrorT(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    })
  })
)
