import { useChat } from '@ai-sdk/react'
import { DefaultChatTransport } from 'ai'
import { useRouter } from 'next/navigation.js'
import { useSession } from 'next-auth/react'
import { useEffect, useRef, useState } from 'react'
import { uuidv7 } from 'uuidv7'
import { isValidUUID, uuidVersionValidation } from 'uuidv7-utilities'

import { fileToDataURL } from '@/application/services/fileToDataURL.service.js'
import { clientEnv } from '@/env/client.js'
import { createLogger } from '@/infrastructure/logging/logger.js'
import { useUserChats } from '@/view/hooks/useUserChats.js'

const logger = createLogger({ prefix: 'useAIChat' })

const MAX_FILE_SIZE = 10 * 1024 * 1024 // 10MB

// Allowed MIME types for file uploads (matching ChatInput accept attribute)
const ALLOWED_FILE_TYPES = [
  // Images
  'image/jpeg',
  'image/png',
  'image/gif',
  'image/webp',
  'image/svg+xml',
  // Documents
  'application/pdf',
  'application/msword', // .doc
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document', // .docx
  'text/plain',
  'text/markdown',
]

interface UseAIChatProps {
  id?: string
  chatTypeParam?: string
  initialMessages?: any[]
}

export function isValidUUIDv7(id: string | Buffer) {
  if (!isValidUUID(id)) {
    return false
  }
  return uuidVersionValidation(id) === 'v7'
}

/**
 * @deprecated Use isValidUUIDv7 instead. This wrapper is kept for backward compatibility.
 */
export function processUserUUID(id: string | Buffer) {
  return isValidUUIDv7(id)
}
export function useAIChat({ chatTypeParam, id, initialMessages }: UseAIChatProps = {}) {
  const router = useRouter()
  const { data: session } = useSession()

  const disabled = !id

  const handleNewChat = () => {
    const newId = uuidv7()
    if (chatTypeParam) {
      logger.info('Creating new chat', {
        chatTypeParam,
        newId,
        event: 'chat.navigation.new-chat-type-param',
      })
      router.push(`/ai/${chatTypeParam}/${newId}`)
    } else {
      logger.info('No chatTypeParam, navigating to landing page', {
        event: 'chat.navigation.landing',
      })
      router.push('/ai')
    }
  }

  // State declarations - must be before useChat to avoid reference errors in callbacks
  const [input, setInput] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [selectedFile, setSelectedFile] = useState<File | null>(null)
  const [errorMessage, setErrorMessage] = useState<string>('')
  const [mobileOpen, setMobileOpen] = useState(false)
  const messagesEndRef = useRef<HTMLDivElement>(null)

  // Fetch user chats
  const {
    data: chats,
    isError: isChatsError,
    isLoading: isLoadingChats,
  } = useUserChats(session?.user?.id ?? null)

  useEffect(() => {
    if (id && !processUserUUID(id)) {
      setErrorMessage('The chat ID is not valid. Only use chat ids auto-generated by the app')
    }
  }, [id])

  logger.debug('Initial messages in useAIChat', {
    messageCount: initialMessages?.length,
    event: 'chat.messages.initialized',
  })

  // Only pass the real chat id to useChat once initialMessages has resolved.
  // useChat treats `messages` as initial state, so if `id` is set before the
  // fetch completes (when initialMessages is still undefined), useChat
  // initialises with an empty message list and ignores the later update.
  // By withholding the real id until we have the data, we guarantee useChat
  // initialises with the correct messages in the same render cycle.
  const activeChatId = initialMessages !== undefined ? id : undefined

  const { messages, sendMessage, status, stop } = useChat({
    id: activeChatId,
    messages: initialMessages,
    transport: new DefaultChatTransport({
      api: clientEnv.NEXT_PUBLIC_POST_AI_CALLBACK_URL,
      ...(chatTypeParam ? { body: { chatTypeParam } } : {}),
      fetch: (url, options) => {
        const accessToken = session?.accessToken
        return fetch(url, {
          ...options,
          credentials: 'include', // Send cookies for authentication
          headers: {
            ...options?.headers,
            ...(accessToken ? { Authorization: `Bearer ${accessToken}` } : {}),
          },
        })
      },
    }),
    onError: (error) => {
      logger.error('Chat transport error', error, {
        event: 'chat.transport.error',
      })
      setErrorMessage(error.message || 'An error occurred while communicating with the AI service')
    },
  })

  useEffect(() => {
    if (!disabled) return
    void stop().catch((error) => {
      logger.error(
        'Error stopping chat transport',
        error instanceof Error ? error : new Error(String(error)),
        {
          event: 'chat.transport.error',
        }
      )
    })
  }, [disabled, stop])

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }

  useEffect(() => {
    scrollToBottom()
  }, [messages])

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!input.trim() || isLoading) return

    setIsLoading(true)

    try {
      const parts: Array<
        { type: 'text'; text: string } | { type: 'file'; mediaType: string; url: string }
      > = [
        {
          type: 'text',
          text: input,
        },
      ]

      if (selectedFile) {
        parts.push({
          type: 'file',
          mediaType: selectedFile.type,
          url: await fileToDataURL(selectedFile),
        })
      }

      await sendMessage({ parts })

      setInput('')
      setSelectedFile(null)
    } finally {
      setIsLoading(false)
    }
  }

  const handleFileSelect = (file: File | null) => {
    if (file) {
      // Validate file size
      if (file.size > MAX_FILE_SIZE) {
        setErrorMessage('File too large. Maximum size is 10MB')
        setSelectedFile(null)
        return
      }

      // Validate file type
      if (!ALLOWED_FILE_TYPES.includes(file.type)) {
        setErrorMessage(
          'Invalid file type. Please upload images, PDFs, Word documents, or text files only.'
        )
        setSelectedFile(null)
        return
      }
    }
    setSelectedFile(file)
  }

  const handleDrawerToggle = () => {
    setMobileOpen(!mobileOpen)
  }

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setInput(e.target.value)
  }

  const handleErrorClose = () => {
    setErrorMessage('')
  }

  const handleNavigateHome = () => {
    router.push('/dashboard')
  }

  const handleSignOut = () => {
    router.push('/api/auth/signout')
  }

  return {
    // State
    messages,
    input,
    isLoading,
    selectedFile,
    errorMessage,
    mobileOpen,
    messagesEndRef,
    disabled,
    userId: session?.user?.id ?? null,
    currentChatId: id,
    status,

    // Chat history
    chats,
    isChatsError,
    isLoadingChats,

    // Accordion configuration
    accordionHeader: 'Chat Information',
    accordionBody:
      'This is an AI-powered chat interface where you can ask questions and get responses.',

    // Handlers
    handleSubmit,
    handleFileSelect,
    handleDrawerToggle,
    handleNewChat,
    handleInputChange,
    handleErrorClose,
    handleNavigateHome,
    handleSignOut,
  }
}
