services:
  # Node.js service (use with: docker compose up nextjs-standalone --build)
  nextjs-standalone:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        NEXT_PUBLIC_POST_AI_CALLBACK_URL: ${NEXT_PUBLIC_POST_AI_CALLBACK_URL}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    image: nextjs-standalone-image
    container_name: nextjs-standalone-container
    env_file:
      - apps/frontend/.env.prod
    environment:
      NODE_ENV: production
      PORT: "3000"
    ports:
      - "3000:3000"
    restart: unless-stopped