import { TransformStream } from 'node:stream/web'
import { promisify } from 'node:util'
import { gunzip as gunzipCb, gzip as gzipCb } from 'node:zlib'

import {
  type LanguageModelV3,
  type LanguageModelV3Middleware,
  type LanguageModelV3StreamPart,
} from '@ai-sdk/provider'
import { UtcDate } from '@norberts-spark/shared'
import { Redis } from '@upstash/redis'
import { simulateReadableStream } from 'ai'
import { obscured } from 'obscured'

import type { LoggerPort } from '../../../application/ports/logger.port.js'
import { EnvConfig } from '../../config/env.config.js'

const gzip = promisify(gzipCb)
const gunzip = promisify(gunzipCb)
/**
 * Cache the evaluated Redis configuration to avoid repeated obscured.value() calls
 */
let isConfiguredCache: boolean | null = null
let cachedRedisUrl: string | undefined
let cachedRedisToken: string | undefined

/**
 * Check if Redis credentials are properly configured
 */
function isRedisConfigured(): boolean {
  // Return cached result if already computed
  if (isConfiguredCache !== null) {
    return isConfiguredCache
  }

  cachedRedisUrl = obscured.value(EnvConfig.UPSTASH_REDIS_REST_URL)
  cachedRedisToken = obscured.value(EnvConfig.UPSTASH_REDIS_REST_TOKEN)

  // Check if credentials exist and are not obscured placeholder values
  isConfiguredCache =
    !!cachedRedisUrl &&
    !!cachedRedisToken &&
    cachedRedisUrl !== '[OBSCURED]' &&
    cachedRedisToken !== '[OBSCURED]' &&
    cachedRedisUrl !== 'undefined' &&
    cachedRedisToken !== 'undefined'

  return isConfiguredCache
}

/**
 * Lazily initialize Redis client only when credentials are configured
 */
let redisClient: Redis | null = null
let initializationAttempted = false

function getRedisClient(logger: LoggerPort): Redis | null {
  // Return existing client if already initialized
  if (redisClient !== null) {
    return redisClient
  }

  // Check if Redis is configured
  if (!isRedisConfigured()) {
    return null
  }

  // Only attempt initialization once to avoid repeated errors
  if (initializationAttempted) {
    return null
  }

  initializationAttempted = true

  try {
    redisClient = new Redis({
      url: cachedRedisUrl!,
      token: cachedRedisToken!,
    })
    return redisClient
  } catch (error) {
    logger.error(
      'Failed to initialize Redis client',
      error instanceof Error ? error : new Error(String(error))
    )
    return null
  }
}

/**
 * Creates a LanguageModelV3Middleware that caches AI responses in Redis.
 *
 * LanguageModelMiddleware has two methods: wrapGenerate and wrapStream. wrapGenerate is called when using generateText and generateObject, while wrapStream is called when using streamText and streamObject.
 * For wrapGenerate, you can cache the response directly. Instead, for wrapStream, you cache an array of the stream parts, which can then be used with simulateReadableStream function to create a simulated ReadableStream that returns the cached response. In this way, the cached response is returned chunk-by-chunk as if it were being generated by the model. You can control the initial delay and delay between chunks by adjusting the initialDelayInMs and chunkDelayInMs parameters of simulateReadableStream.
 * https://ai-sdk.dev/docs/advanced/caching
 *
 * @param logger - Pino-backed logger used for debug/error messages
 */
export function createCacheMiddleware(logger: LoggerPort): LanguageModelV3Middleware {
  return {
    specificationVersion: 'v3',
    wrapGenerate: async ({ doGenerate, params }) => {
      const cacheKey = JSON.stringify(params)
      const redis = getRedisClient(logger)

      // Try to get from cache if Redis is configured
      if (redis) {
        try {
          const raw = (await redis.get(cacheKey)) as string | null

          if (raw !== null) {
            const cached = JSON.parse(
              (await gunzip(Buffer.from(raw, 'base64'))).toString()
            ) as Awaited<ReturnType<LanguageModelV3['doGenerate']>>

            logger.debug('wrapGenerate: cache hit — returning cached response', {
              middleware: 'cache-middleware',
            })
            return {
              ...cached,
              response: {
                ...cached.response,
                timestamp: cached?.response?.timestamp
                  ? new Date(cached?.response?.timestamp)
                  : undefined,
              },
            }
          }

          logger.debug('wrapGenerate: cache miss — calling model', {
            middleware: 'cache-middleware',
          })
        } catch (error) {
          logger.error(
            'Cache read error in wrapGenerate',
            error instanceof Error ? error : new Error(String(error)),
            { middleware: 'cache-middleware' }
          )
          // Continue without cache - graceful degradation
        }
      }

      const result = await doGenerate()

      // Try to cache the result if Redis is configured
      if (redis) {
        try {
          const compressed = (await gzip(Buffer.from(JSON.stringify(result)))).toString('base64')
          await redis.set(cacheKey, compressed, { ex: 3600 })
          logger.debug('wrapGenerate: response written to cache', {
            middleware: 'cache-middleware',
          })
        } catch (error) {
          logger.error(
            'Cache write error in wrapGenerate',
            error instanceof Error ? error : new Error(String(error)),
            { middleware: 'cache-middleware' }
          )
          // Continue without caching - graceful degradation
        }
      }

      return result
    },
    wrapStream: async ({ doStream, params }) => {
      const cacheKey = JSON.stringify(params)
      const redis = getRedisClient(logger)

      // Try to check if the result is in the cache if Redis is configured
      if (redis) {
        try {
          const raw = (await redis.get(cacheKey)) as string | null

          // If cached, return a simulated ReadableStream that yields the cached result
          if (raw !== null) {
            const cached = JSON.parse(
              (await gunzip(Buffer.from(raw, 'base64'))).toString()
            ) as LanguageModelV3StreamPart[]

            logger.debug('wrapStream: cache hit — returning simulated stream', {
              middleware: 'cache-middleware',
            })
            // Format the timestamps in the cached response
            const formattedChunks = cached.map((p) => {
              if (p.type === 'response-metadata' && p.timestamp) {
                return { ...p, timestamp: UtcDate.create(p.timestamp).toDate() }
              } else return p
            })
            return {
              stream: simulateReadableStream({
                initialDelayInMs: 0,
                chunkDelayInMs: 10,
                chunks: formattedChunks,
              }),
            }
          }
          logger.debug('wrapStream: cache miss — calling model', { middleware: 'cache-middleware' })
        } catch (error) {
          logger.error(
            'Cache read error in wrapStream',
            error instanceof Error ? error : new Error(String(error)),
            { middleware: 'cache-middleware' }
          )
          // Continue without cache - graceful degradation
        }
      }

      // If not cached, proceed with streaming
      const { stream, ...rest } = await doStream()

      const fullResponse: LanguageModelV3StreamPart[] = []

      const transformStream = new TransformStream<
        LanguageModelV3StreamPart,
        LanguageModelV3StreamPart
      >({
        transform(chunk, controller) {
          fullResponse.push(chunk)
          controller.enqueue(chunk)
        },
        async flush() {
          // Try to store the full response in the cache after streaming is complete if Redis is configured
          if (redis) {
            try {
              const compressed = (await gzip(Buffer.from(JSON.stringify(fullResponse)))).toString(
                'base64'
              )
              await redis.set(cacheKey, compressed, { ex: 3600 })
              logger.debug('wrapStream: response written to cache', {
                middleware: 'cache-middleware',
              })
            } catch (error) {
              logger.error(
                'Cache write error in wrapStream flush',
                error instanceof Error ? error : new Error(String(error)),
                { middleware: 'cache-middleware' }
              )
              // Continue without caching - graceful degradation
            }
          }
        },
      })

      return {
        stream: stream.pipeThrough(transformStream),
        ...rest,
      }
    },
  }
}
