import { TransformStream } from 'node:stream/web'

import {
  type LanguageModelV3,
  type LanguageModelV3Middleware,
  type LanguageModelV3StreamPart,
} from '@ai-sdk/provider'
import { UtcDate } from '@norberts-spark/shared'
import { simulateReadableStream } from 'ai'

import { getRedisClient } from '../../redis/index.js'

/**
 * LanguageModelMiddleware has two methods: wrapGenerate and wrapStream. wrapGenerate is called when using generateText and generateObject, while wrapStream is called when using streamText and streamObject.
 * For wrapGenerate, you can cache the response directly. Instead, for wrapStream, you cache an array of the stream parts, which can then be used with simulateReadableStream function to create a simulated ReadableStream that returns the cached response. In this way, the cached response is returned chunk-by-chunk as if it were being generated by the model. You can control the initial delay and delay between chunks by adjusting the initialDelayInMs and chunkDelayInMs parameters of simulateReadableStream.
 * https://ai-sdk.dev/docs/advanced/caching
 */

export const cacheMiddleware: LanguageModelV3Middleware = {
  specificationVersion: 'v3',
  wrapGenerate: async ({ doGenerate, params }) => {
    const cacheKey = JSON.stringify(params)
    const redis = getRedisClient()

    // Try to get from cache if Redis is configured
    if (redis) {
      try {
        const raw = await redis.get(cacheKey)
        const cached = raw
          ? (JSON.parse(raw) as Awaited<ReturnType<LanguageModelV3['doGenerate']>>)
          : null

        if (cached !== null) {
          return {
            ...cached,
            response: {
              ...cached.response,
              timestamp: cached?.response?.timestamp
                ? UtcDate.create(cached.response.timestamp).toDate()
                : undefined,
            },
          }
        }
      } catch (error) {
        console.error('Cache read error in wrapGenerate:', error)
        // Continue without cache - graceful degradation
      }
    }

    const result = await doGenerate()

    // Try to cache the result if Redis is configured
    if (redis) {
      try {
        await redis.set(cacheKey, JSON.stringify(result))
      } catch (error) {
        console.error('Cache write error in wrapGenerate:', error)
        // Continue without caching - graceful degradation
      }
    }

    return result
  },
  wrapStream: async ({ doStream, params }) => {
    const cacheKey = JSON.stringify(params)
    const redis = getRedisClient()

    // Try to check if the result is in the cache if Redis is configured
    if (redis) {
      try {
        const rawStream = await redis.get(cacheKey)

        // If cached, return a simulated ReadableStream that yields the cached result
        if (rawStream !== null) {
          // Format the timestamps in the cached response
          const formattedChunks = (JSON.parse(rawStream) as LanguageModelV3StreamPart[]).map(
            (p) => {
              if (p.type === 'response-metadata' && p.timestamp) {
                return { ...p, timestamp: UtcDate.create(p.timestamp).toDate() }
              } else return p
            }
          )
          return {
            stream: simulateReadableStream({
              initialDelayInMs: 0,
              chunkDelayInMs: 10,
              chunks: formattedChunks,
            }),
          }
        }
      } catch (error) {
        console.error('Cache read error in wrapStream:', error)
        // Continue without cache - graceful degradation
      }
    }

    // If not cached, proceed with streaming
    const { stream, ...rest } = await doStream()

    const fullResponse: LanguageModelV3StreamPart[] = []

    const transformStream = new TransformStream<
      LanguageModelV3StreamPart,
      LanguageModelV3StreamPart
    >({
      transform(chunk, controller) {
        fullResponse.push(chunk)
        controller.enqueue(chunk)
      },
      async flush() {
        // Try to store the full response in the cache after streaming is complete if Redis is configured
        if (redis) {
          try {
            await redis.set(cacheKey, JSON.stringify(fullResponse))
          } catch (error) {
            console.error('Cache write error in wrapStream flush:', error)
            // Continue without caching - graceful degradation
          }
        }
      },
    })

    return {
      stream: stream.pipeThrough(transformStream),
      ...rest,
    }
  },
}
