/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod/v4-mini'
import { NorbertsSparkSDKCore } from '../core.js'
import { encodeSimple } from '../lib/encodings.js'
import * as M from '../lib/matchers.js'
import { compactMap } from '../lib/primitives.js'
import { safeParse } from '../lib/schemas.js'
import { RequestOptions } from '../lib/sdks.js'
import { extractSecurity, resolveGlobalSecurity } from '../lib/security.js'
import { pathToFunc } from '../lib/url.js'
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from '../models/errors/http-client-errors.js'
import * as errors from '../models/errors/index.js'
import { NorbertsSparkSDKError } from '../models/errors/norberts-spark-sdk-error.js'
import { ResponseValidationError } from '../models/errors/response-validation-error.js'
import { SDKValidationError } from '../models/errors/sdk-validation-error.js'
import * as operations from '../models/operations/index.js'
import { APICall, APIPromise } from '../types/async.js'
import { Result } from '../types/fp.js'
import * as types$ from '../types/primitives.js'

/**
 * Fetch data extracted from PDFs
 *
 * @remarks
 * Retrieves the data from the PDF file previously uploaded to bucket
 */
export function aiExtractData(
  client: NorbertsSparkSDKCore,
  request: operations.ExtractDataRequest,
  options?: RequestOptions
): APIPromise<
  Result<
    string,
    | errors.ErrorT
    | NorbertsSparkSDKError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(client, request, options))
}

async function $do(
  client: NorbertsSparkSDKCore,
  request: operations.ExtractDataRequest,
  options?: RequestOptions
): Promise<
  [
    Result<
      string,
      | errors.ErrorT
      | NorbertsSparkSDKError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) => z.parse(operations.ExtractDataRequest$outboundSchema, value),
    'Input validation failed'
  )
  if (!parsed.ok) {
    return [parsed, { status: 'invalid' }]
  }
  const payload = parsed.value
  const body = null

  const pathParams = {
    fileId: encodeSimple('fileId', payload.fileId, {
      explode: false,
      charEncoding: 'percent',
    }),
  }

  const path = pathToFunc('/ai/extract-data/{fileId}')(pathParams)

  const headers = new Headers(
    compactMap({
      Accept: 'text/plain',
    })
  )

  const secConfig = await extractSecurity(client._options.bearerAuth)
  const securityInput = secConfig == null ? {} : { bearerAuth: secConfig }
  const requestSecurity = resolveGlobalSecurity(securityInput)

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? '',
    operationID: 'extractData',
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: client._options.bearerAuth,
    retryConfig: options?.retries || client._options.retryConfig || { strategy: 'none' },
    retryCodes: options?.retryCodes || ['429', '500', '502', '503', '504'],
  }

  const requestRes = client._createRequest(
    context,
    {
      security: requestSecurity,
      method: 'GET',
      baseURL: options?.serverURL,
      path: path,
      headers: headers,
      body: body,
      userAgent: client._options.userAgent,
      timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
    },
    options
  )
  if (!requestRes.ok) {
    return [requestRes, { status: 'invalid' }]
  }
  const req = requestRes.value

  const doResult = await client._do(req, {
    context,
    errorCodes: ['401', '403', '404', '4XX', '500', '5XX'],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  })
  if (!doResult.ok) {
    return [doResult, { status: 'request-error', request: req }]
  }
  const response = doResult.value

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  }

  const [result] = await M.match<
    string,
    | errors.ErrorT
    | NorbertsSparkSDKError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.text(200, types$.string()),
    M.jsonErr([401, 403, 404], errors.ErrorT$inboundSchema),
    M.jsonErr(500, errors.ErrorT$inboundSchema),
    M.fail('4XX'),
    M.fail('5XX')
  )(response, req, { extraFields: responseFields })
  if (!result.ok) {
    return [result, { status: 'complete', request: req, response }]
  }

  return [result, { status: 'complete', request: req, response }]
}
