/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { aiExtractData } from '../funcs/ai-extract-data.js'
import { aiGeneratePresignedUrls } from '../funcs/ai-generate-presigned-urls.js'
import { aiGetAIChatDetails } from '../funcs/ai-get-ai-chat-details.js'
import { aiGetAIChatSettingsById } from '../funcs/ai-get-ai-chat-settings-by-id.js'
import { aiGetAIChatsByUserId } from '../funcs/ai-get-ai-chats-by-user-id.js'
import { aiGetAIFetchChatByChatId } from '../funcs/ai-get-ai-fetch-chat-by-chat-id.js'
import { aiGetAIResponse } from '../funcs/ai-get-ai-response.js'
import { aiPutAIChatSettingsById } from '../funcs/ai-put-ai-chat-settings-by-id.js'
import { ClientSDK, RequestOptions } from '../lib/sdks.js'
import * as models from '../models/index.js'
import * as operations from '../models/operations/index.js'
import { unwrapAsync } from '../types/fp.js'

export class Ai extends ClientSDK {
  /**
   * Get AI-generated response
   *
   * @remarks
   * Sends a prompt to the AI service and retrieves the generated response
   */
  async getAIResponse(request: models.AIRequest, options?: RequestOptions): Promise<string> {
    return unwrapAsync(aiGetAIResponse(this, request, options))
  }

  /**
   * Get chat IDs for user
   *
   * @remarks
   * Retrieves a list of chat IDs associated with the specified user
   */
  async getAIChatsByUserId(
    request: operations.GetAIChatsByUserIdRequest,
    options?: RequestOptions
  ): Promise<models.AIUserIdResponse> {
    return unwrapAsync(aiGetAIChatsByUserId(this, request, options))
  }

  /**
   * Fetch chat by chatId
   *
   * @remarks
   * Retrieves the chat object for the specified chatId
   */
  async getAIFetchChatByChatId(
    request: operations.GetAIFetchChatByChatIdRequest,
    options?: RequestOptions
  ): Promise<models.AIfetchChatResponse> {
    return unwrapAsync(aiGetAIFetchChatByChatId(this, request, options))
  }

  /**
   * Generate presigned URLs for direct R2 upload
   *
   * @remarks
   * Accepts file metadata (filename and mimetype) and returns presigned URLs for direct upload to Cloudflare R2 storage. The client can then use these URLs to upload files directly without going through the backend.
   */
  async generatePresignedUrls(
    request: operations.GeneratePresignedUrlsRequest,
    options?: RequestOptions
  ): Promise<operations.GeneratePresignedUrlsResponse> {
    return unwrapAsync(aiGeneratePresignedUrls(this, request, options))
  }

  /**
   * Fetch data extracted from PDFs
   *
   * @remarks
   * Retrieves the data from the PDF file previously uploaded to bucket
   */
  async extractData(
    request: operations.ExtractDataRequest,
    options?: RequestOptions
  ): Promise<string> {
    return unwrapAsync(aiExtractData(this, request, options))
  }

  /**
   * Get chat AI configuration
   *
   * @remarks
   * Retrieves all available chat types with their details and SEO-friendly identifiers
   */
  async getAIChatDetails(options?: RequestOptions): Promise<models.AIChatOptionsResponse> {
    return unwrapAsync(aiGetAIChatDetails(this, options))
  }

  /**
   * Get specific chat AI settings by ID
   *
   * @remarks
   * Retrieves AI configuration settings for a specific chat type using its unique identifier
   */
  async getAIChatSettingsById(
    request: operations.GetAIChatSettingsByIdRequest,
    options?: RequestOptions
  ): Promise<models.AIChatOptionResponse> {
    return unwrapAsync(aiGetAIChatSettingsById(this, request, options))
  }

  /**
   * Update specific chat AI settings by ID
   *
   * @remarks
   * Updates (replaces) AI configuration settings for a specific chat type using its unique identifier. Returns 404 if the chat configuration does not exist.
   */
  async putAIChatSettingsById(
    request: operations.PutAIChatSettingsByIdRequest,
    options?: RequestOptions
  ): Promise<void> {
    return unwrapAsync(aiPutAIChatSettingsById(this, request, options))
  }
}
