/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authLoginUser } from '../funcs/auth-login-user.js'
import { authOauthSync } from '../funcs/auth-oauth-sync.js'
import { ClientSDK, RequestOptions } from '../lib/sdks.js'
import * as models from '../models/index.js'
import * as operations from '../models/operations/index.js'
import { unwrapAsync } from '../types/fp.js'

export class Auth extends ClientSDK {
  /**
   * Authenticate a user
   *
   * @remarks
   * Authenticates a user and returns a JWT access token
   */
  async loginUser(
    request: models.UserLoginRequest,
    options?: RequestOptions
  ): Promise<models.UserLoginResponse> {
    return unwrapAsync(authLoginUser(this, request, options))
  }

  /**
   * Synchronize OAuth user data
   *
   * @remarks
   * Creates or updates user records for OAuth-authenticated users (Google, GitHub, etc.). This endpoint is called by the frontend NextAuth callback to ensure OAuth users are stored in the backend database for consistency with credentials users. Protected by a shared secret header to prevent unauthorized access.
   */
  async oauthSync(
    security: operations.OauthSyncSecurity,
    request: models.OAuthSyncRequest,
    options?: RequestOptions
  ): Promise<models.OAuthSyncResponse> {
    return unwrapAsync(authOauthSync(this, security, request, options))
  }
}
