/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { aiExtractData } from "../funcs/ai-extract-data.js";
import { aiGetAIChatDetails } from "../funcs/ai-get-ai-chat-details.js";
import { aiGetAIChatSettingsById } from "../funcs/ai-get-ai-chat-settings-by-id.js";
import { aiGetAIChatsByUserId } from "../funcs/ai-get-ai-chats-by-user-id.js";
import { aiGetAIFetchChatByChatId } from "../funcs/ai-get-ai-fetch-chat-by-chat-id.js";
import { aiPutAIChatSettingsById } from "../funcs/ai-put-ai-chat-settings-by-id.js";
import { chatGetChatTypes } from "../funcs/chat-get-chat-types.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Chat extends ClientSDK {
  /**
   * Get chat IDs for user
   *
   * @remarks
   * Retrieves a list of chat IDs associated with the specified user
   */
  async getAIChatsByUserId(
    request: operations.GetAIChatsByUserIdRequest,
    options?: RequestOptions,
  ): Promise<models.AIUserIdResponse> {
    return unwrapAsync(aiGetAIChatsByUserId(
      this,
      request,
      options,
    ));
  }

  /**
   * Fetch chat by chatId
   *
   * @remarks
   * Retrieves the chat object for the specified chatId
   */
  async getAIFetchChatByChatId(
    request: operations.GetAIFetchChatByChatIdRequest,
    options?: RequestOptions,
  ): Promise<models.AIfetchChatResponse> {
    return unwrapAsync(aiGetAIFetchChatByChatId(
      this,
      request,
      options,
    ));
  }

  /**
   * Fetch data extracted from PDFs
   *
   * @remarks
   * Retrieves the data from the PDF file previously uploaded to bucket
   */
  async extractData(
    request: operations.ExtractDataRequest,
    options?: RequestOptions,
  ): Promise<string> {
    return unwrapAsync(aiExtractData(
      this,
      request,
      options,
    ));
  }

  /**
   * Get chat AI configuration
   *
   * @remarks
   * Retrieves all available chat types with their details and SEO-friendly identifiers
   */
  async getAIChatDetails(
    options?: RequestOptions,
  ): Promise<models.AIChatOptionsResponse> {
    return unwrapAsync(aiGetAIChatDetails(
      this,
      options,
    ));
  }

  /**
   * Get list of chat types
   *
   * @remarks
   * Retrieve a list of available chat types that can be used for communication.
   */
  async getChatTypes(
    security: operations.GetChatTypesSecurity,
    options?: RequestOptions,
  ): Promise<models.ChatTypesResponse> {
    return unwrapAsync(chatGetChatTypes(
      this,
      security,
      options,
    ));
  }

  /**
   * Get specific chat AI settings by ID
   *
   * @remarks
   * Retrieves AI configuration settings for a specific chat type using its unique identifier
   */
  async getAIChatSettingsById(
    request: operations.GetAIChatSettingsByIdRequest,
    options?: RequestOptions,
  ): Promise<models.AIChatOptionResponse> {
    return unwrapAsync(aiGetAIChatSettingsById(
      this,
      request,
      options,
    ));
  }

  /**
   * Update specific chat AI settings by ID
   *
   * @remarks
   * Updates (replaces) AI configuration settings for a specific chat type using its unique identifier. Returns 404 if the chat configuration does not exist.
   */
  async putAIChatSettingsById(
    request: operations.PutAIChatSettingsByIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(aiPutAIChatSettingsById(
      this,
      request,
      options,
    ));
  }
}
