/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { companyGetCompanyDetails } from '../funcs/company-get-company-details.js'
import { companyUpdateCompanyDetails } from '../funcs/company-update-company-details.js'
import { ClientSDK, RequestOptions } from '../lib/sdks.js'
import * as models from '../models/index.js'
import * as operations from '../models/operations/index.js'
import { unwrapAsync } from '../types/fp.js'

export class Company extends ClientSDK {
  /**
   * Get Company and key person details
   *
   * @remarks
   * Retrieve detailed information about the single company record and the single key person record (each table contains at most one record)
   */
  async getCompanyDetails(options?: RequestOptions): Promise<models.CompanyDetailsResponse> {
    return unwrapAsync(companyGetCompanyDetails(this, options))
  }

  /**
   * Update Company and key person details
   *
   * @remarks
   * Update the single company record and the single key person record (each table contains at most one record)
   */
  async updateCompanyDetails(
    security: operations.UpdateCompanyDetailsSecurity,
    request: models.CompanyDetailsRequest,
    options?: RequestOptions
  ): Promise<void> {
    return unwrapAsync(companyUpdateCompanyDetails(this, security, request, options))
  }
}
