/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { aiGeneratePresignedUrls } from "../funcs/ai-generate-presigned-urls.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Data extends ClientSDK {
  /**
   * Generate presigned URLs for direct R2 upload
   *
   * @remarks
   * Accepts file metadata (filename and mimetype) and returns presigned URLs for direct upload to Cloudflare R2 storage. The client can then use these URLs to upload files directly without going through the backend.
   */
  async generatePresignedUrls(
    request: operations.GeneratePresignedUrlsRequest,
    options?: RequestOptions,
  ): Promise<operations.GeneratePresignedUrlsResponse> {
    return unwrapAsync(aiGeneratePresignedUrls(
      this,
      request,
      options,
    ));
  }
}
