/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersDeleteUsers } from '../funcs/users-delete-users.js'
import { usersGetAllUsers } from '../funcs/users-get-all-users.js'
import { usersGetUserById } from '../funcs/users-get-user-by-id.js'
import { usersRegisterUser } from '../funcs/users-register-user.js'
import { ClientSDK, RequestOptions } from '../lib/sdks.js'
import * as models from '../models/index.js'
import * as operations from '../models/operations/index.js'
import { unwrapAsync } from '../types/fp.js'

export class Users extends ClientSDK {
  /**
   * Register a new user
   *
   * @remarks
   * Creates a new user account
   */
  async registerUser(
    request: models.RegisterUserRequest,
    options?: RequestOptions
  ): Promise<models.RegisterUserResponse> {
    return unwrapAsync(usersRegisterUser(this, request, options))
  }

  /**
   * Get user by ID
   *
   * @remarks
   * Retrieves a user's profile information
   */
  async getUserById(
    request: operations.GetUserByIdRequest,
    options?: RequestOptions
  ): Promise<models.User> {
    return unwrapAsync(usersGetUserById(this, request, options))
  }

  /**
   * Get all users
   *
   * @remarks
   * Retrieves all users in date order with pagination. Requires authentication with admin or moderator role.
   */
  async getAllUsers(
    request?: operations.GetAllUsersRequest | undefined,
    options?: RequestOptions
  ): Promise<models.PaginatedUsersResponse> {
    return unwrapAsync(usersGetAllUsers(this, request, options))
  }

  /**
   * Delete users
   *
   * @remarks
   * Deletes multiple user accounts by their IDs. Requires authentication with admin role.
   */
  async deleteUsers(
    request: operations.DeleteUsersRequest,
    options?: RequestOptions
  ): Promise<operations.DeleteUsersResponse> {
    return unwrapAsync(usersDeleteUsers(this, request, options))
  }
}
