/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod/v4-mini'
import { safeParse } from '../../lib/schemas.js'
import { Result as SafeParseResult } from '../../types/fp.js'
import * as types from '../../types/primitives.js'
import { SDKValidationError } from '../errors/sdk-validation-error.js'

export type DeleteUsersRequest = {
  /**
   * Array of user IDs to delete (1-10 items)
   */
  userIds: Array<string>
}

/**
 * Users successfully deleted
 */
export type DeleteUsersResponse = {
  success: boolean
  message: string
}

/** @internal */
export type DeleteUsersRequest$Outbound = {
  userIds: Array<string>
}

/** @internal */
export const DeleteUsersRequest$outboundSchema: z.ZodMiniType<
  DeleteUsersRequest$Outbound,
  DeleteUsersRequest
> = z.object({
  userIds: z.array(z.string()),
})

export function deleteUsersRequestToJSON(deleteUsersRequest: DeleteUsersRequest): string {
  return JSON.stringify(DeleteUsersRequest$outboundSchema.parse(deleteUsersRequest))
}

/** @internal */
export const DeleteUsersResponse$inboundSchema: z.ZodMiniType<DeleteUsersResponse, unknown> =
  z.object({
    success: types.boolean(),
    message: types.string(),
  })

export function deleteUsersResponseFromJSON(
  jsonString: string
): SafeParseResult<DeleteUsersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteUsersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteUsersResponse' from JSON`
  )
}
