/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod/v4-mini'

export type ExtractDataRequest = {
  /**
   * The unique identifier for the file in the bucket
   */
  fileId: string
}

/** @internal */
export type ExtractDataRequest$Outbound = {
  fileId: string
}

/** @internal */
export const ExtractDataRequest$outboundSchema: z.ZodMiniType<
  ExtractDataRequest$Outbound,
  ExtractDataRequest
> = z.object({
  fileId: z.string(),
})

export function extractDataRequestToJSON(extractDataRequest: ExtractDataRequest): string {
  return JSON.stringify(ExtractDataRequest$outboundSchema.parse(extractDataRequest))
}
