/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type FileT = {
  /**
   * Name of the file
   */
  filename: string;
  /**
   * MIME type of the file
   */
  mimetype: string;
};

export type GeneratePresignedUrlsRequest = {
  /**
   * Array of file metadata objects
   */
  files: Array<FileT>;
};

export type UploadUrl = {
  /**
   * Original filename
   */
  filename: string;
  /**
   * Presigned URL for direct upload to R2
   */
  uploadUrl: string;
  /**
   * Storage key for the file in R2
   */
  fileKey: string;
};

export type Data = {
  uploadUrls: Array<UploadUrl>;
};

/**
 * Presigned URLs generated successfully
 */
export type GeneratePresignedUrlsResponse = {
  success: boolean;
  data: Data;
  message?: string | undefined;
};

/** @internal */
export type FileT$Outbound = {
  filename: string;
  mimetype: string;
};

/** @internal */
export const FileT$outboundSchema: z.ZodMiniType<FileT$Outbound, FileT> = z
  .object({
    filename: z.string(),
    mimetype: z.string(),
  });

export function fileToJSON(fileT: FileT): string {
  return JSON.stringify(FileT$outboundSchema.parse(fileT));
}

/** @internal */
export type GeneratePresignedUrlsRequest$Outbound = {
  files: Array<FileT$Outbound>;
};

/** @internal */
export const GeneratePresignedUrlsRequest$outboundSchema: z.ZodMiniType<
  GeneratePresignedUrlsRequest$Outbound,
  GeneratePresignedUrlsRequest
> = z.object({
  files: z.array(z.lazy(() => FileT$outboundSchema)),
});

export function generatePresignedUrlsRequestToJSON(
  generatePresignedUrlsRequest: GeneratePresignedUrlsRequest,
): string {
  return JSON.stringify(
    GeneratePresignedUrlsRequest$outboundSchema.parse(
      generatePresignedUrlsRequest,
    ),
  );
}

/** @internal */
export const UploadUrl$inboundSchema: z.ZodMiniType<UploadUrl, unknown> = z
  .object({
    filename: types.string(),
    uploadUrl: types.string(),
    fileKey: types.string(),
  });

export function uploadUrlFromJSON(
  jsonString: string,
): SafeParseResult<UploadUrl, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadUrl$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadUrl' from JSON`,
  );
}

/** @internal */
export const Data$inboundSchema: z.ZodMiniType<Data, unknown> = z.object({
  uploadUrls: z.array(z.lazy(() => UploadUrl$inboundSchema)),
});

export function dataFromJSON(
  jsonString: string,
): SafeParseResult<Data, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Data$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Data' from JSON`,
  );
}

/** @internal */
export const GeneratePresignedUrlsResponse$inboundSchema: z.ZodMiniType<
  GeneratePresignedUrlsResponse,
  unknown
> = z.object({
  success: types.boolean(),
  data: z.lazy(() => Data$inboundSchema),
  message: types.optional(types.string()),
});

export function generatePresignedUrlsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GeneratePresignedUrlsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeneratePresignedUrlsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeneratePresignedUrlsResponse' from JSON`,
  );
}
