/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod/v4-mini'
import { safeParse } from '../../lib/schemas.js'
import * as openEnums from '../../types/enums.js'
import { OpenEnum } from '../../types/enums.js'
import { Result as SafeParseResult } from '../../types/fp.js'
import * as types from '../../types/primitives.js'
import { SDKValidationError } from '../errors/sdk-validation-error.js'

export const Status = {
  Ok: 'ok',
  Degraded: 'degraded',
  Down: 'down',
} as const
export type Status = OpenEnum<typeof Status>

/**
 * Service is healthy
 */
export type GetHealthResponse = {
  status: Status
  timestamp: Date
}

/** @internal */
export const Status$inboundSchema: z.ZodMiniType<Status, unknown> = openEnums.inboundSchema(Status)

/** @internal */
export const GetHealthResponse$inboundSchema: z.ZodMiniType<GetHealthResponse, unknown> = z.object({
  status: Status$inboundSchema,
  timestamp: types.date(),
})

export function getHealthResponseFromJSON(
  jsonString: string
): SafeParseResult<GetHealthResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetHealthResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetHealthResponse' from JSON`
  )
}
