/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetChatTypesSecurity = {
  oauthSyncSecret: string;
};

/** @internal */
export type GetChatTypesSecurity$Outbound = {
  oauthSyncSecret: string;
};

/** @internal */
export const GetChatTypesSecurity$outboundSchema: z.ZodMiniType<
  GetChatTypesSecurity$Outbound,
  GetChatTypesSecurity
> = z.object({
  oauthSyncSecret: z.string(),
});

export function getChatTypesSecurityToJSON(
  getChatTypesSecurity: GetChatTypesSecurity,
): string {
  return JSON.stringify(
    GetChatTypesSecurity$outboundSchema.parse(getChatTypesSecurity),
  );
}
