/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod/v4-mini'

export type GetAIChatSettingsByIdRequest = {
  /**
   * The unique identifier for the chat option
   */
  id: string
}

/** @internal */
export type GetAIChatSettingsByIdRequest$Outbound = {
  id: string
}

/** @internal */
export const GetAIChatSettingsByIdRequest$outboundSchema: z.ZodMiniType<
  GetAIChatSettingsByIdRequest$Outbound,
  GetAIChatSettingsByIdRequest
> = z.object({
  id: z.string(),
})

export function getAIChatSettingsByIdRequestToJSON(
  getAIChatSettingsByIdRequest: GetAIChatSettingsByIdRequest
): string {
  return JSON.stringify(
    GetAIChatSettingsByIdRequest$outboundSchema.parse(getAIChatSettingsByIdRequest)
  )
}
