/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetAIFetchChatByChatIdRequest = {
  /**
   * The chat's unique identifier
   */
  chatId: string;
};

/** @internal */
export type GetAIFetchChatByChatIdRequest$Outbound = {
  chatId: string;
};

/** @internal */
export const GetAIFetchChatByChatIdRequest$outboundSchema: z.ZodMiniType<
  GetAIFetchChatByChatIdRequest$Outbound,
  GetAIFetchChatByChatIdRequest
> = z.object({
  chatId: z.string(),
});

export function getAIFetchChatByChatIdRequestToJSON(
  getAIFetchChatByChatIdRequest: GetAIFetchChatByChatIdRequest,
): string {
  return JSON.stringify(
    GetAIFetchChatByChatIdRequest$outboundSchema.parse(
      getAIFetchChatByChatIdRequest,
    ),
  );
}
