/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod/v4-mini'

export type GetAllUsersRequest = {
  /**
   * Number of items to skip
   */
  offset?: number | undefined
  /**
   * Number of items per page
   */
  limit?: number | undefined
}

/** @internal */
export type GetAllUsersRequest$Outbound = {
  offset: number
  limit: number
}

/** @internal */
export const GetAllUsersRequest$outboundSchema: z.ZodMiniType<
  GetAllUsersRequest$Outbound,
  GetAllUsersRequest
> = z.object({
  offset: z._default(z.int(), 0),
  limit: z._default(z.int(), 10),
})

export function getAllUsersRequestToJSON(getAllUsersRequest: GetAllUsersRequest): string {
  return JSON.stringify(GetAllUsersRequest$outboundSchema.parse(getAllUsersRequest))
}
