/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod/v4-mini'

export type GetAIChatsByUserIdRequest = {
  /**
   * The user's unique identifier whose chat history is being retrieved
   */
  userId: string
}

/** @internal */
export type GetAIChatsByUserIdRequest$Outbound = {
  userId: string
}

/** @internal */
export const GetAIChatsByUserIdRequest$outboundSchema: z.ZodMiniType<
  GetAIChatsByUserIdRequest$Outbound,
  GetAIChatsByUserIdRequest
> = z.object({
  userId: z.string(),
})

export function getAIChatsByUserIdRequestToJSON(
  getAIChatsByUserIdRequest: GetAIChatsByUserIdRequest
): string {
  return JSON.stringify(GetAIChatsByUserIdRequest$outboundSchema.parse(getAIChatsByUserIdRequest))
}
