/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod/v4-mini'

export type GetUserByIdRequest = {
  /**
   * The user's unique identifier
   */
  id: string
}

/** @internal */
export type GetUserByIdRequest$Outbound = {
  id: string
}

/** @internal */
export const GetUserByIdRequest$outboundSchema: z.ZodMiniType<
  GetUserByIdRequest$Outbound,
  GetUserByIdRequest
> = z.object({
  id: z.string(),
})

export function getUserByIdRequestToJSON(getUserByIdRequest: GetUserByIdRequest): string {
  return JSON.stringify(GetUserByIdRequest$outboundSchema.parse(getUserByIdRequest))
}
