/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod/v4-mini'

export type OauthSyncSecurity = {
  oauthSyncSecret: string
}

/** @internal */
export type OauthSyncSecurity$Outbound = {
  oauthSyncSecret: string
}

/** @internal */
export const OauthSyncSecurity$outboundSchema: z.ZodMiniType<
  OauthSyncSecurity$Outbound,
  OauthSyncSecurity
> = z.object({
  oauthSyncSecret: z.string(),
})

export function oauthSyncSecurityToJSON(oauthSyncSecurity: OauthSyncSecurity): string {
  return JSON.stringify(OauthSyncSecurity$outboundSchema.parse(oauthSyncSecurity))
}
