/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type PutAIChatSettingsByIdRequest = {
  /**
   * The unique identifier for the chat option
   */
  id: string;
  body: models.PutRequestAIChatSettings;
};

/** @internal */
export type PutAIChatSettingsByIdRequest$Outbound = {
  id: string;
  body: models.PutRequestAIChatSettings$Outbound;
};

/** @internal */
export const PutAIChatSettingsByIdRequest$outboundSchema: z.ZodMiniType<
  PutAIChatSettingsByIdRequest$Outbound,
  PutAIChatSettingsByIdRequest
> = z.object({
  id: z.string(),
  body: models.PutRequestAIChatSettings$outboundSchema,
});

export function putAIChatSettingsByIdRequestToJSON(
  putAIChatSettingsByIdRequest: PutAIChatSettingsByIdRequest,
): string {
  return JSON.stringify(
    PutAIChatSettingsByIdRequest$outboundSchema.parse(
      putAIChatSettingsByIdRequest,
    ),
  );
}
