/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type UpdateCompanyDetailsSecurity = {
  oauthSyncSecret: string;
};

/** @internal */
export type UpdateCompanyDetailsSecurity$Outbound = {
  oauthSyncSecret: string;
};

/** @internal */
export const UpdateCompanyDetailsSecurity$outboundSchema: z.ZodMiniType<
  UpdateCompanyDetailsSecurity$Outbound,
  UpdateCompanyDetailsSecurity
> = z.object({
  oauthSyncSecret: z.string(),
});

export function updateCompanyDetailsSecurityToJSON(
  updateCompanyDetailsSecurity: UpdateCompanyDetailsSecurity,
): string {
  return JSON.stringify(
    UpdateCompanyDetailsSecurity$outboundSchema.parse(
      updateCompanyDetailsSecurity,
    ),
  );
}
